# GitHub workflow file
name: Javascript linter

on:
  push:
    # change(s) on those files trigger this pipeline
    paths: ['*.js', '.eslintrc.json', '.github/workflows/linters.yml']

jobs:
  linters:   # run linters in separate job to not delay critical stuff
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Copy the repository
        uses: actions/checkout@v2.0.0
      
      # Node 10 is current default in ubuntu-latest (https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md)
      # then we install 12, same as for AWS Lambda
      - name: Install Node 12
        uses: actions/setup-node@v1.4.1
        with:
          node-version: 12

      - name: Cache node modules
        uses: actions/cache@v1.1.2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install nodejs packages listed in package-lock.json.
      # - if: github.base_ref == 'master'
      - name: Install node modules
        run: |
          npm install eslint --save-dev
          npm install --save-dev --save-exact prettier
          npm ci --only=prod
  
      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          prettier: false
